# Generated by Django 3.2 on 2026-02-20 06:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighmentSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_type', models.CharField(blank=True, choices=[('aggregator', 'aggregator'), ('grower', 'grower')], max_length=150, null=True)),
                ('mode_of_supply', models.CharField(blank=True, choices=[('By hand', 'By hand'), ('By Non motorised 2/3 wheelers vehicle', 'By Non motorised 2/3 wheelers vehicle'), ('Motorised 2 wheelers vehicle', 'Motorised 2 wheelers vehicle'), ('Motorised 3 / 4 wheelers vehicle', 'Motorised 3 / 4 wheelers vehicle')], max_length=150, null=True)),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('total_gross_weight_kg', models.FloatField(blank=True, help_text='Kg', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('mobile_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Not a valid Mobile Number', regex='^\\+?1?\\d{6,10}$')])),
                ('weighment_txn_id', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_leaf_rejected', models.BooleanField(default=False)),
                ('is_supplier_exit_proceed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_user', to=settings.AUTH_USER_MODEL)),
                ('supply_challan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supply_challan_id_supply_management', to='user_profile.supplymanagement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weighment_vehicle_id', to='vehicle_management.vehiclemanagement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlfSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(blank=True, max_length=150, null=True)),
                ('aggregator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_aggregator_supplier', to='user_profile.aggregatorprofile')),
                ('blf', models.ManyToManyField(blank=True, null=True, related_name='blfs_aggregators_supplier', to='user_profile.BlfProfile')),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_grower_supplier', to='user_profile.aggregatorprofile')),
            ],
        ),
    ]
