# Generated by Django 3.2 on 2026-02-20 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weighment_supply', '0001_initial'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_management', '0001_initial'),
        ('user_profile', '0001_initial'),
        ('gardens_managment', '0002_initial'),
        ('tea_production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierexit',
            name='weighment_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_weighment_id', to='weighment_supply.weighmentsupply'),
        ),
        migrations.AddField(
            model_name='shgcooperativetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shgcooperativetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shgcooperativeprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shgcooperativeprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_shg_cooperative_district', to='master.district'),
        ),
        migrations.AddField(
            model_name='shgcooperativeprofile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_type_shg_cooperative', to='user_profile.profiletype'),
        ),
        migrations.AddField(
            model_name='shgcooperativeprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_shg_cooperative_region', to='master.region'),
        ),
        migrations.AddField(
            model_name='shgcooperativeprofile',
            name='shg_cooperative_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shg_type', to='user_profile.shgcooperativetype'),
        ),
        migrations.AddField(
            model_name='shgcooperativeprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_shg_cooperative_state', to='master.state'),
        ),
        migrations.AddField(
            model_name='shgcooperativeprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shgcooperativeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_shg_cooperative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_district', to='master.district'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_region', to='master.region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_state', to='master.state'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_type', to='user_profile.profiletype'),
        ),
        migrations.AddField(
            model_name='pluckingdata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pluckingdata',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_id', to='gardens_managment.division'),
        ),
        migrations.AddField(
            model_name='pluckingdata',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower_id_pluckingdata', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='pluckingdata',
            name='labour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labour_id', to='user_profile.labour'),
        ),
        migrations.AddField(
            model_name='pluckingdata',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_id_pluckingdata', to='gardens_managment.plot'),
        ),
        migrations.AddField(
            model_name='pluckingdata',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grower_id_monthly_schedule', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_year', to='user_profile.year'),
        ),
        migrations.AddField(
            model_name='labour',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_labour', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='labour',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_labour', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='labour',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labour',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_grower_labour', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='labour',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growertype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growertype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growerqrcode',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower_qr', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='associated_aggregator',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_associated_aggregator', to='user_profile.AggregatorProfile'),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='associated_entity',
            field=models.ManyToManyField(blank=True, null=True, related_name='grower_associated_entity', to='user_profile.BlfProfile'),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='associated_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_grower_asso_unit', to='master.associatedunit'),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_grower_district', to='master.district'),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_type_grower', to='user_profile.profiletype'),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_grower_region', to='master.region'),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_grower_state', to='master.state'),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_grower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growerdetailssupply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growerdetailssupply',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collected_grower_id_supply', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='growerdetailssupply',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_id', to='user_profile.supplymanagement'),
        ),
        migrations.AddField(
            model_name='growerdetailssupply',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factorytroughdetails',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estate_trough_factorty', to='user_profile.estateprofile'),
        ),
        migrations.AddField(
            model_name='factorytroughdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_trough_factorty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factorydetailsmarks',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_factory_marks', to='user_profile.estateprofile'),
        ),
        migrations.AddField(
            model_name='estatetroughdetails',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_trough_details', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='estatetroughdetails',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_trough_details_factory', to='user_profile.factorytroughdetails'),
        ),
        migrations.AddField(
            model_name='estateteaproduction',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea_production_estate', to='user_profile.estateprofile'),
        ),
        migrations.AddField(
            model_name='estateteaproduction',
            name='tea_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea_type_grade_production', to='tea_production.teagradedetails'),
        ),
        migrations.AddField(
            model_name='estateteaproduction',
            name='tea_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea_type', to='tea_production.teatype'),
        ),
        migrations.AddField(
            model_name='estateprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estateprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_estate_district', to='master.district'),
        ),
        migrations.AddField(
            model_name='estateprofile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_type_estate', to='user_profile.profiletype'),
        ),
        migrations.AddField(
            model_name='estateprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_estate_region', to='master.region'),
        ),
        migrations.AddField(
            model_name='estateprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_estate_state', to='master.state'),
        ),
        migrations.AddField(
            model_name='estateprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estateprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_estate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estateproductionteatype',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_production_tea_type', to='user_profile.estateprofile'),
        ),
        migrations.AddField(
            model_name='estateproductionteatype',
            name='tea_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_tea_type_grade_production', to='tea_production.teagradedetails'),
        ),
        migrations.AddField(
            model_name='estateproductionteatype',
            name='tea_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_tea_type', to='tea_production.teatype'),
        ),
        migrations.AddField(
            model_name='consigneeprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consigneeprofile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_type_consignee', to='user_profile.profiletype'),
        ),
        migrations.AddField(
            model_name='consigneeprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_consignee_region', to='master.region'),
        ),
        migrations.AddField(
            model_name='consigneeprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consigneeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_consignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionfromgrower',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionfromgrower',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_collection_from_grower', to='gardens_managment.division'),
        ),
        migrations.AddField(
            model_name='collectionfromgrower',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_grower_id', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='collectionfromgrower',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_plot_id', to='gardens_managment.plot'),
        ),
        migrations.AddField(
            model_name='collectionfromgrower',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionfromgrower',
            name='vehicle_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_vehicle_number', to='vehicle_management.vehiclemanagement'),
        ),
        migrations.AddField(
            model_name='collectionfromaggregator',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_aggregator_collection_id', to='user_profile.aggregatorprofile'),
        ),
        migrations.AddField(
            model_name='collectionfromaggregator',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionfromaggregator',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_collection_from_aggregator', to='gardens_managment.division'),
        ),
        migrations.AddField(
            model_name='collectionfromaggregator',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_plot_id_aggregator', to='gardens_managment.plot'),
        ),
        migrations.AddField(
            model_name='collectionfromaggregator',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionfromaggregator',
            name='vehicle_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_vehicle_number_aggregator', to='vehicle_management.vehiclemanagement'),
        ),
        migrations.AddField(
            model_name='blftroughdetails',
            name='user_profile_blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_trough_details', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='blfteaproduction',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea_productions_blf', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='blfteaproduction',
            name='tea_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea_type_grade_productions_blf', to='tea_production.teagradedetails'),
        ),
        migrations.AddField(
            model_name='blfteaproduction',
            name='tea_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea_type_blf', to='tea_production.teatype'),
        ),
        migrations.AddField(
            model_name='blfprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blfprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_blf_district', to='master.district'),
        ),
        migrations.AddField(
            model_name='blfprofile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_type_blf', to='user_profile.profiletype'),
        ),
        migrations.AddField(
            model_name='blfprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_blf_region', to='master.region'),
        ),
        migrations.AddField(
            model_name='blfprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_blf_state', to='master.state'),
        ),
        migrations.AddField(
            model_name='blfprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blfprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_blf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blfofficialsignature',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blf_signature', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='blfofficialsignature',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blfofficialsignature',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blffactorymarks',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_factorys_marks', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='blffactorydetailsmarks',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_factory_details_marks', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='blfassociatedusers',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_associated_aggregators', to='user_profile.aggregatorprofile'),
        ),
        migrations.AddField(
            model_name='blfassociatedusers',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='blfassociatedusers',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_associated_growers', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='aggregatortype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aggregatortype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aggregatorqrcode',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_qr_code', to='user_profile.aggregatorprofile'),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='associated_aggregator',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_profile_aggregatorprofile_associated_aggregator_+', to='user_profile.AggregatorProfile'),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='associated_entity',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_aggregator_entity', to='user_profile.BlfProfile'),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_aggregator_district', to='master.district'),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_type_aggregator', to='user_profile.profiletype'),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_aggregator_region', to='master.region'),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_aggregator_state', to='master.state'),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_aggregator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisoryprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisoryprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_advisory_user_district', to='master.district'),
        ),
        migrations.AddField(
            model_name='advisoryprofile',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_type_advisory_user', to='user_profile.profiletype'),
        ),
        migrations.AddField(
            model_name='advisoryprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_advisory_user_region', to='master.region'),
        ),
        migrations.AddField(
            model_name='advisoryprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_advisory_user_state', to='master.state'),
        ),
        migrations.AddField(
            model_name='advisoryprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisoryprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_advisory_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
