# Generated by Django 3.2 on 2026-03-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_labour', to='user_profile.aggregatorprofile'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blf_labour', to='user_profile.blfprofile'),
        ),
    ]
