# Generated by Django 3.2 on 2026-03-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20260313_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aggregator_monthly_schedule', to='user_profile.growerprofile'),
        ),
    ]
