# Generated by Django 3.2 on 2026-03-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_supplymanagement_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplymanagement',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
