# Generated by Django 3.2 on 2026-03-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_supplymanagement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='growerprofile',
            name='poi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='poi_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
