# Generated by Django 3.2 on 2026-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20260330_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growerprofile',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('AADHAR CARD', 'AADHAR CARD'), ('VOTER ID', 'VOTER ID'), ('TBOI CARD', 'TBOI CARD'), ('RC ID', 'RC ID'), ('DL ID', 'DL'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
