# Generated by Django 3.2 on 2026-04-07 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0008_alter_growerprofile_id_proof_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='growerprofile',
            name='driving_licence_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='pan_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='ration_card_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='growerprofile',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='growerprofile',
            name='voter_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfileAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('doc_type', models.CharField(blank=True, choices=[('id_proof', 'ID Proff'), ('profile_image', 'Profile Image')], default='id_proof', max_length=250, null=True)),
                ('attachment_name', models.CharField(blank=True, choices=[('AADHAR_CARD', 'AADHAR CARD'), ('VOTER_ID', 'VOTER ID'), ('TBOI_CARD', 'TBOI CARD'), ('RC_ID', 'RC ID'), ('DL_ID', 'DL'), ('Other', 'Other')], default='', max_length=250, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='users/profile/ID')),
                ('mime_type', models.CharField(blank=True, max_length=200, null=True)),
                ('file_data', models.TextField(blank=True, null=True)),
                ('doc_no', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower_proof_id_attachments', to='user_profile.growerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile_attachments',
            },
        ),
    ]
