# Generated by Django 3.2 on 2026-04-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20260407_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growerprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='growerprofile',
            name='username',
        ),
    ]
