# Generated by Django 3.2 on 2026-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20260407_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='growerprofile',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='growerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
