# Generated by Django 3.2 on 2026-04-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20260407_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growerprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='growerprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
    ]
