# Generated by Django 3.2 on 2026-04-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20260408_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
