# Generated by Django 3.2 on 2026-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_monthlyscheduledayhoursdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyschedule',
            name='monthly_wages',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyscheduledayhoursdetails',
            name='days',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyscheduledayhoursdetails',
            name='hour',
            field=models.FloatField(default=0),
        ),
    ]
