# Generated by Django 3.2 on 2026-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_auto_20260409_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='hourly_rate',
            field=models.FloatField(default=0),
        ),
    ]
