# Generated by Django 3.2 on 2026-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_monthlyschedule_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluckingdata',
            name='labours',
            field=models.ManyToManyField(blank=True, null=True, related_name='labour_ids', to='user_profile.Labour'),
        ),
    ]
