# Generated by Django 3.2 on 2026-02-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lot_batch_details', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlist',
            name='lot_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batchlist_lot_no', to='lot_batch_details.lotbatchdetails'),
        ),
    ]
