# Generated by Django 3.2 on 2026-02-20 06:19

import django.core.validators
from django.db import migrations, models
import user_profile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_local_name', models.CharField(blank=True, max_length=200, null=True)),
                ('composition', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmersAggreementForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('farmer_signature_file', models.FileField(blank=True, help_text='file', null=True, upload_to='BLF/Farmers/Aggreement', validators=[user_profile.validators.validate_signature_file_extension])),
                ('blf_grade_official_signature_file', models.FileField(blank=True, help_text='file', null=True, upload_to='BLF/Farmers/Aggreement', validators=[user_profile.validators.validate_signature_file_extension])),
                ('date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmersAggreementMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapAreaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('total_areas', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('map_image', models.FileField(blank=True, help_text='file', null=True, upload_to='map_details/file', validators=[user_profile.validators.validate_image_file_extension])),
                ('coordinate', models.JSONField(blank=True, null=True)),
                ('water_source', models.TextField(blank=True, null=True)),
                ('land_near_by', models.TextField(blank=True, null=True)),
                ('is_image_upload', models.BooleanField(blank=True, default=False, null=True)),
                ('is_digital_upload', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapAreaLandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('total_areas', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('coordinate', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapAreaMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('map_image', models.FileField(blank=True, help_text='file', null=True, upload_to='map_details/file', validators=[user_profile.validators.validate_image_file_extension])),
                ('pdf_map_image', models.FileField(blank=True, help_text='file', null=True, upload_to='map_details/file', validators=[user_profile.validators.validate_image_file_extension])),
                ('digital_map_image', models.FileField(blank=True, help_text='file', null=True, upload_to='map_details/file/digital-map', validators=[user_profile.validators.validate_image_file_extension])),
                ('water_source', models.TextField(blank=True, null=True)),
                ('land_near_by', models.TextField(blank=True, null=True)),
                ('is_image_upload', models.BooleanField(blank=True, default=False, null=True)),
                ('is_digital_upload', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapAreaNameMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UseOfChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
