# Generated by Django 3.2 on 2026-02-20 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemical_data', '0001_initial'),
        ('user_profile', '0001_initial'),
        ('gardens_managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useofchemical',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_chemical_blf', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='useofchemical',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_chemical_grower', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='useofchemical',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_data_id', to='chemical_data.chemicaldata'),
        ),
        migrations.AddField(
            model_name='useofchemical',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useofchemical',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_use_of_chemical', to='gardens_managment.division'),
        ),
        migrations.AddField(
            model_name='useofchemical',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_chemical_aggregator', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='useofchemical',
            name='labour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labour_id_chemical', to='user_profile.labour'),
        ),
        migrations.AddField(
            model_name='useofchemical',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_id_chemical', to='gardens_managment.plot'),
        ),
        migrations.AddField(
            model_name='useofchemical',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapareanamemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapareanamemaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapareamaster',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aggregator_map_area_master', to='user_profile.aggregatorprofile'),
        ),
        migrations.AddField(
            model_name='mapareamaster',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blf_map_area_master', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='mapareamaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapareamaster',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grower_map_area_master', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='mapareamaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maparealanddetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maparealanddetails',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grower_map_area_land_details', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='maparealanddetails',
            name='map_area_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_area_land_details', to='chemical_data.mapareamaster'),
        ),
        migrations.AddField(
            model_name='maparealanddetails',
            name='map_area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_area_name_land_details', to='chemical_data.mapareanamemaster'),
        ),
        migrations.AddField(
            model_name='maparealanddetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapareadetails',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aggregator_map_area_details', to='user_profile.aggregatorprofile'),
        ),
        migrations.AddField(
            model_name='mapareadetails',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blf_map_area_details', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='mapareadetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapareadetails',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grower_map_area_details', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='mapareadetails',
            name='map_area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_area_name', to='chemical_data.mapareanamemaster'),
        ),
        migrations.AddField(
            model_name='mapareadetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmersaggreementmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmersaggreementmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmersaggreementforms',
            name='aggreement_form_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmers_aggreement_title', to='chemical_data.farmersaggreementmaster'),
        ),
        migrations.AddField(
            model_name='farmersaggreementforms',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aggregator_aggreements', to='user_profile.aggregatorprofile'),
        ),
        migrations.AddField(
            model_name='farmersaggreementforms',
            name='blf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blf_farmer_aggreements', to='user_profile.blfprofile'),
        ),
        migrations.AddField(
            model_name='farmersaggreementforms',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmersaggreementforms',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grower_aggreements', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='farmersaggreementforms',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemicaltype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemicaltype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemicaldata',
            name='chemical_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_type_trusttea', to='chemical_data.chemicaltype'),
        ),
        migrations.AddField(
            model_name='chemicaldata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_chemical', to=settings.AUTH_USER_MODEL),
        ),
    ]
