# Generated by Django 3.2 on 2026-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_data', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersaggreementforms',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmersaggreementforms',
            name='mime_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
