# Generated by Django 3.2 on 2026-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_data', '0003_auto_20260317_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='useofchemical',
            name='dose',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
