# Generated by Django 3.2 on 2026-03-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_data', '0004_useofchemical_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapareadetails',
            name='map_image',
            field=models.FileField(blank=True, null=True, upload_to='map_details/file'),
        ),
    ]
