# Generated by Django 3.2 on 2026-03-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_data', '0005_alter_mapareadetails_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapareadetails',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapareadetails',
            name='mime_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
