# Generated by Django 3.2 on 2026-04-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_pluckingdata_labours'),
        ('chemical_data', '0006_auto_20260327_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maparealanddetails',
            name='map_area_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_area_land_details', to='chemical_data.mapareamaster'),
        ),
        migrations.AlterField(
            model_name='mapareamaster',
            name='grower',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grower_map_area_master', to='user_profile.growerprofile'),
        ),
    ]
