# Generated by Django 3.2 on 2026-02-20 06:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(blank=True, max_length=150, null=True)),
                ('nt_wght', models.FloatField(blank=True, help_text='(Kg)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeafManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction', models.FloatField(blank=True, help_text='(%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_leaf_count', models.FloatField(blank=True, help_text='(%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('acknowledge_status', models.CharField(blank=True, choices=[('Received', 'Received'), ('Rejected', 'Rejected')], max_length=50, null=True)),
                ('quality_standard', models.CharField(blank=True, choices=[('A', 'A'), ('A+', 'A+'), ('B', 'B'), ('B+', 'B+'), ('C', 'C'), ('C+', 'C+'), ('D+', 'D+'), ('D', 'D')], max_length=50, null=True)),
                ('payment_record_option', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('rate', models.CharField(blank=True, max_length=200, null=True)),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('net_leaf_weight', models.FloatField(blank=True, help_text='(Kg)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_complete', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_leaf_receipt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
