# Generated by Django 3.2 on 2026-02-20 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weighment_supply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaf_receipt', '0001_initial'),
        ('user_profile', '0001_initial'),
        ('gardens_managment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafmanagement',
            name='weighment_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weignment_supply_txn_id', to='weighment_supply.weighmentsupply'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregators_leafcollect', to='user_profile.aggregatorprofile'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='grower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower_leafcollect', to='user_profile.growerprofile'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='grower_garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower_garden_leafcollect', to='gardens_managment.gardens'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='grower_plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grower_plot_leafcollect', to='gardens_managment.plot'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='leaf_receipt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaf_receipt_collection', to='leaf_receipt.leafmanagement'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='plucking_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plucking_data_leafcollect', to='user_profile.pluckingdata'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='suppler_exit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_exit_collection', to='user_profile.supplierexit'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_leafcollect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='supply_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplymanagment_collection', to='user_profile.supplymanagement'),
        ),
        migrations.AddField(
            model_name='leafcollection',
            name='weighment_supply_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighment_collection', to='weighment_supply.weighmentsupply'),
        ),
    ]
