# Generated by Django 3.2 on 2026-02-20 06:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tea_production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagSlNoRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_sl_no_range', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotBatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_batch_no', models.CharField(max_length=200)),
                ('lot_batch_date', models.DateField(blank=True, null=True)),
                ('bag_sl_no_from', models.IntegerField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sl_no_to', models.IntegerField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bag_sl_no_range', models.CharField(blank=True, max_length=150, null=True)),
                ('bag_weight_kg', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_lot', to='tea_production.teagradedetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
