# Generated by Django 3.2 on 2026-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehiclemanagement',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted=False), fields=('vehicle_number',), name='unique_vehicle_number_if_not_deleted'),
        ),
    ]
