# Generated by Django 3.2 on 2026-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0002_vehiclemanagement_unique_vehicle_number_if_not_deleted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclemanagement',
            name='unique_vehicle_number_if_not_deleted',
        ),
        migrations.AlterField(
            model_name='vehiclemanagement',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
